# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 16:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesession',
            name='repo_tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
